// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelExport():Promise<void>;

export function ChooseFolder():Promise<string>;

export function Connect(arg1:string,arg2:string,arg3:boolean):Promise<main.ConnectResult>;

export function LoadSettings():Promise<main.Settings>;

export function StartExport(arg1:main.ExportRequest):Promise<void>;
