// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelExport() {
  return window['go']['main']['App']['CancelExport']();
}

export function ChooseFolder() {
  return window['go']['main']['App']['ChooseFolder']();
}

export function Connect(arg1, arg2, arg3) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3);
}

export function Discover() {
  return window['go']['main']['App']['Discover']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function StartExport(arg1) {
  return window['go']['main']['App']['StartExport'](arg1);
}
